### ISSUE TITLE
"Missing executable" on Steam 

### ISSUE THREAD

**Issue by vpltd-peterm** [virtual-programming/overlord2-linux#1] opened 2016-07-26 22:13 UTC
We're aware that some people are getting this message.

If you have made a new purchase from today on Steam, please indicate that here.
If you have made a previous purchase, please use Account Details and check how you acquired it. It may have been part of a package bundle that we are currently unable to modify, but have asked Codemasters to look at.

It is also possible that the content has not spread to all of Steam's download servers yet. In this case, try switching Download Region in Steam

**Comment by vpltd-peterm** [comment] 2016-07-26 23:51
I've just updated a whole bunch of sales packages for the Overlord games that were overlooked at first. Hopefully this should largely resolve the issues being seen.

**Comment by deresh** [comment] 2016-07-30 06:49
@vpltd-peterm:

I still have issues with all Overlord games: Overlord, Overlord: Raising hell, Overlord 2.

Overlord reports it has only 135Mb of files, Raising Hell and Overlord 2 just start downloading (they don't download anything, neither they report a download size). 

And as expected it doesn't work ("Missing executable" error for all of them).

I got all of those games through "Humble Codemasters bundle". In this bundle i also got "Dirt Showdown" and when Linux version became available, game installed and played correctly.

Also i'm using Steam on Linux (Ubuntu 16.04) with latest Nvidia drivers.

**Comment by vpltd-peterm** [comment] 2016-07-30 13:51
Codemasters need to update those bundles, and we have requested that they do so. We do not have access to those bundles on Steam to do it.
Dirt Showdown is present there because they updated the bundles to include it when we released the game.

**Comment by deresh** [comment] 2016-07-30 14:05
@vpltd-peterm:

Ok, thanx for info. Can i help in some way?

**Comment by vpltd-peterm** [comment] 2016-07-31 02:28
I don't think so... I will notify my boss and see if we can speed things up

**Comment by deresh** [comment] 2016-08-06 07:34
Any news on this, @vpltd-peterm ?

**Comment by vpltd-peterm** [comment] 2016-08-10 14:50
Codemasters have advised us that bundles that were available to purchase prior to the release of the Mac and Linux version do not qualify for a free copy of the game for the new platforms. These special bundles were sold purely for the supported platform at that time.

**Comment by XavCamp** [comment] 2016-08-10 15:50
That's an awful decision to take, very nice for the customers. And we can't even buy a Mac/Linux compatible version on Steam because Steam says that we already own the game.
I know it's not your call, but it's very disappointing.

**Comment by vpltd-peterm** [comment] 2016-08-10 16:00
Hmm, you are correct that you cannot repurchase, I will speak to them about this as we may be able to resolve that with Steam.

**Comment by deresh** [comment] 2016-08-10 17:58
Well, that is just awfull :( I Know that is not your's fault, but as XavCamp said, we cannot repurchase those game(s) even i we would like to :/

Hope this gets resolved somehow!

**Comment by vpltd-plesurf** [comment] 2016-08-12 10:56
Hi,

I can confirm I have managed to get approval for all the past packages to be updated.
If you don't see access to Linux/Mac builds in the coming 48 hours please advise.

Regards.

**Comment by deresh** [comment] 2016-08-12 19:23
Excellent! Thank you for your effort. Will notify u if all is ok after 48h.

br

**Comment by deresh** [comment] 2016-08-17 20:27
@vpltd-plesurf:

Hi, i just wanted to notify you, things still haven't changed and it passed 5 days.
I'm in no hurry, but you stated that if things don't change in 48h to send you an update.

**Comment by deresh** [comment] 2016-08-24 16:50
This is fixed now for me. I have sucesfully downloaded game and started playing.

Thank you guys! @vpltd-plesurf  @vpltd-peterm

**Closed** 2016-08-25 11:51 UTC
